services:
  fiap-erp:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - 8081:8080
    depends_on:
      mysql-restaurant:
        condition: service_healthy
    environment:
      MYSQL_URL: jdbc:mysql://mysql-restaurant:3306/fiap-restaurant?autoReconnect=true&useSSL=false&allowPublicKeyRetrieval=true
    networks:
      - fiap-network
  mysql-restaurant:
    image: mysql:8.0
    volumes:
      - mysql_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_DATABASE: fiap-restaurant
      MYSQL_PASSWORD: pwd-fiap
      MYSQL_ROOT_PASSWORD: root-fiap
      MYSQL_USER: user-fiap
    ports:
      - 3306:3306
    networks:
      - fiap-network
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      retries: 3
      interval: 30s
      timeout: 30s
volumes:
  mysql_data: {}

networks:
  fiap-network:
    driver: bridge